name: 'run'

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'setup python'
      uses: actions/setup-python@master
      with: 
         python-version: 3.7
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      env:
         SCKEY: ${{ secrets.SCKEY }}
         username: ${{ secrets.username }}
         password: ${{ secrets.password }}
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        random_time=$(($RANDOM % 45))
        echo "等待 ${random_time} 分钟后开始签到"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done
        for ((i=0;i<$user_num;i++))
        do
        python3 ./Cloud189Checkin/C189Checkin.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done    

